name = "tiktok-lark-analytics"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
LARK_APP_TOKEN = "VhAWbo2gia2uKSsLQATjoI9cpje"
LARK_TABLE_ID = "tblNj0k7qnw3K4xg"
LARK_VIEW_ID = "vew8E3SU2J"
