export interface TikTokVideoRecord { itemId:string; videoCreateTime:string|null; recordCreatedTime:string; thumbnail:string|null; caption:string; hashtags:string; likes:number; shares:number; comments:number; videoViews:number; viewUsers:number; videoDuration:number; totalTimeWatched:number; averageTimeWatched:number; fullVideoWatchedRate:number; embedUrl:string|null; shareUrl:string|null; impressionSources:{follow:number;feed:number;tag:number;profile:number;sound:number;search:number}; week:string;year:number;month:number;day:number;totalEngagement:number;lastUpdatedTime:string|null }
export interface AnalyticsPoint { key:string; label:string; videos:number; views:number; likes:number; shares:number; comments:number; engagement:number; engagementRate:number }
export type DailyAnalytics=AnalyticsPoint; export type WeeklyAnalytics=AnalyticsPoint; export type MonthlyAnalytics=AnalyticsPoint;
export interface SummaryComparison { totalVideos:number;newVideos:number;totalViews:number;totalLikes:number;totalShares:number;totalComments:number;engagementRate:number;averageFullWatchRate:number;newVideoViews:number;newVideoLikes:number;newVideoShares:number;newVideoComments:number;newVideoEngagementRate:number;newVideoFullWatchRate:number }
export interface SummaryAnalytics { totalVideos:number;newVideos:number;totalViews:number;totalLikes:number;totalShares:number;totalComments:number;totalEngagement:number;engagementRate:number;averageFullWatchRate:number;newVideoViews:number;newVideoLikes:number;newVideoShares:number;newVideoComments:number;newVideoEngagementRate:number;newVideoFullWatchRate:number;lastSync:string|null;totalRecords:number;comparison?:SummaryComparison }
export interface TrafficSourceAnalytics { key:"feed"|"follow"|"profile"|"search"|"sound";label:string;value:number;percentage:number }
export interface KeywordAnalytics { keyword:string;occurrences:number;views:number;videos:number }
export interface TopicAnalytics { topic:string;videos:number;views:number;averageViews:number;averageEngagementRate:number }
export interface AnalyticsResponse<T>{data:T;meta:{totalRecords:number;lastSync:string|null;cached:boolean}}
