"use client";
import { BarChart3,ChartNoAxesCombined,Flame,Hash,LayoutDashboard,Menu,Tags,X } from "lucide-react";
import { cn } from "@/lib/utils";
import { useState } from "react";

export type View="overview"|"analytics"|"viral"|"traffic"|"keywords"|"topics";
const items:[View,string,typeof LayoutDashboard][]=[["overview","Tổng quan",LayoutDashboard],["analytics","Phân tích",BarChart3],["viral","Viral video",Flame],["traffic","Nguồn truy cập",ChartNoAxesCombined],["keywords","Phân tích hashtag",Hash],["topics","Chủ đề",Tags]];
export function Sidebar({view,onView}:{view:View;onView:(v:View)=>void}){
 const[open,setOpen]=useState(false);
 const nav=<><div className="flex min-h-[78px] items-center gap-3 border-b border-white/10 px-5 py-3"><div className="grid size-10 shrink-0 place-items-center rounded-lg bg-brand-600 text-white shadow-lg shadow-brand-950/30"><ChartNoAxesCombined size={20}/></div><div className="min-w-0"><p className="text-sm font-bold text-white">TikTok Analytics</p><a href="https://www.tiktok.com/@anlanhmotchut.duockhong" target="_blank" rel="noopener noreferrer" title="Mở kênh TikTok An Lành Một Chút" className="mt-1 inline-flex max-w-full rounded border border-slate-700 bg-white/5 px-1.5 py-0.5 text-[10px] font-medium text-slate-300 hover:border-brand-400 hover:bg-brand-500/10 hover:text-white"><span className="truncate">Kênh: An Lành Một Chút</span></a></div></div><div className="px-5 pb-2 pt-6 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Không gian phân tích</div><nav className="scrollbar flex-1 overflow-y-auto px-3 pb-4">{items.map(([id,label,Icon])=><button key={id} onClick={()=>{onView(id);setOpen(false)}} className={cn("group mb-1 flex w-full cursor-pointer items-center gap-3 rounded-md border px-3 py-2.5 text-left text-sm font-medium",view===id?"border-brand-500/30 bg-brand-600 text-white shadow-sm":"border-transparent text-slate-400 hover:bg-white/5 hover:text-white")}><Icon size={18} className={cn("shrink-0",view===id?"text-white":"text-slate-500 group-hover:text-brand-400")}/><span className="min-w-0 truncate">{label}</span>{view===id&&<span className="ml-auto size-1.5 rounded-full bg-amber-400"/>}</button>)}</nav></>;
 return <><button aria-label="Mở menu" onClick={()=>setOpen(true)} className="fixed left-4 top-4 z-30 grid size-10 cursor-pointer place-items-center rounded-md border border-slate-200 bg-white text-slate-700 shadow-sm lg:hidden"><Menu size={19}/></button><aside className="sticky top-0 hidden h-[100dvh] w-64 shrink-0 flex-col bg-slate-950 lg:flex">{nav}</aside>{open&&<div className="fixed inset-0 z-40 bg-slate-950/50 backdrop-blur-sm lg:hidden" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()} className="flex h-full w-72 flex-col bg-slate-950 shadow-2xl"><button aria-label="Đóng menu" onClick={()=>setOpen(false)} className="absolute left-[232px] top-5 grid size-8 cursor-pointer place-items-center rounded-md text-slate-400 hover:bg-white/10 hover:text-white"><X size={20}/></button>{nav}</aside></div>}</>
}
